// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy/terraform-provider-cribl-terraform/internal/sdk/internal/utils"
	"time"
)

type State string

const (
	StateWorkspaceRequested                 State = "Workspace-Requested"
	StateWorkspaceProvisioning              State = "Workspace-Provisioning"
	StateWorkspaceProvisioningFailed        State = "Workspace-Provisioning-Failed"
	StateWorkspaceProvisioned               State = "Workspace-Provisioned"
	StateWorkspaceActive                    State = "Workspace-Active"
	StateWorkspaceUpdated                   State = "Workspace-Updated"
	StateWorkspaceFailedUpdate              State = "Workspace-Failed-Update"
	StateWorkspaceCleanupRequested          State = "Workspace-Cleanup-Requested"
	StateWorkspaceCleanupStarted            State = "Workspace-Cleanup-Started"
	StateWorkspaceCleanupTerraformCompleted State = "Workspace-Cleanup-Terraform-Completed"
	StateWorkspaceCleanupTerraformFailed    State = "Workspace-Cleanup-Terraform-Failed"
	StateWorkspaceCleanupCompleted          State = "Workspace-Cleanup-Completed"
	StateWorkspaceCleanupFailed             State = "Workspace-Cleanup-Failed"
)

func (e State) ToPointer() *State {
	return &e
}
func (e *State) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Workspace-Requested":
		fallthrough
	case "Workspace-Provisioning":
		fallthrough
	case "Workspace-Provisioning-Failed":
		fallthrough
	case "Workspace-Provisioned":
		fallthrough
	case "Workspace-Active":
		fallthrough
	case "Workspace-Updated":
		fallthrough
	case "Workspace-Failed-Update":
		fallthrough
	case "Workspace-Cleanup-Requested":
		fallthrough
	case "Workspace-Cleanup-Started":
		fallthrough
	case "Workspace-Cleanup-Terraform-Completed":
		fallthrough
	case "Workspace-Cleanup-Terraform-Failed":
		fallthrough
	case "Workspace-Cleanup-Completed":
		fallthrough
	case "Workspace-Cleanup-Failed":
		*e = State(v)
		return nil
	default:
		return fmt.Errorf("invalid value for State: %v", v)
	}
}

type WorkspaceDTO struct {
	Alias       *string   `json:"alias,omitempty"`
	Description *string   `json:"description,omitempty"`
	Tags        []string  `json:"tags,omitempty"`
	WorkspaceID string    `json:"workspaceId"`
	Region      string    `json:"region"`
	LastUpdated time.Time `json:"lastUpdated"`
	LeaderFQDN  string    `json:"leaderFQDN"`
	State       State     `json:"state"`
}

func (w WorkspaceDTO) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(w, "", false)
}

func (w *WorkspaceDTO) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &w, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *WorkspaceDTO) GetAlias() *string {
	if o == nil {
		return nil
	}
	return o.Alias
}

func (o *WorkspaceDTO) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *WorkspaceDTO) GetTags() []string {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *WorkspaceDTO) GetWorkspaceID() string {
	if o == nil {
		return ""
	}
	return o.WorkspaceID
}

func (o *WorkspaceDTO) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *WorkspaceDTO) GetLastUpdated() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.LastUpdated
}

func (o *WorkspaceDTO) GetLeaderFQDN() string {
	if o == nil {
		return ""
	}
	return o.LeaderFQDN
}

func (o *WorkspaceDTO) GetState() State {
	if o == nil {
		return State("")
	}
	return o.State
}
