workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Cribl API Reference:
        inputs:
            - location: openapi.yml
        registry:
            location: registry.speakeasyapi.dev/cribl/cribl/cribl-api-reference
targets:
    cribl-terraform:
        target: terraform
        source: Cribl API Reference
        publish:
            terraform:
                gpgPrivateKey: $terraform_gpg_private_key
                gpgPassPhrase: $terraform_gpg_passphrase
