// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type FiftyThree struct {
	Connections  []Input53Connections `tfsdk:"connections"`
	CurrentBoot  types.Bool           `tfsdk:"current_boot"`
	Description  types.String         `tfsdk:"description"`
	Disabled     types.Bool           `tfsdk:"disabled"`
	Environment  types.String         `tfsdk:"environment"`
	ID           types.String         `tfsdk:"id"`
	Interval     types.Number         `tfsdk:"interval"`
	Journals     []types.String       `tfsdk:"journals"`
	MaxAgeDur    types.String         `tfsdk:"max_age_dur"`
	Metadata     []Input53Metadata    `tfsdk:"metadata"`
	Path         types.String         `tfsdk:"path"`
	Pipeline     types.String         `tfsdk:"pipeline"`
	Pq           *Input53Pq           `tfsdk:"pq"`
	PqEnabled    types.Bool           `tfsdk:"pq_enabled"`
	Rules        []InputRules         `tfsdk:"rules"`
	SendToRoutes types.Bool           `tfsdk:"send_to_routes"`
	Status       *Input53Status       `tfsdk:"status"`
	Streamtags   []types.String       `tfsdk:"streamtags"`
	Type         types.String         `tfsdk:"type"`
}
