// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type FiftyOne struct {
	BatchSize           types.Number         `tfsdk:"batch_size"`
	Connections         []Input51Connections `tfsdk:"connections"`
	Description         types.String         `tfsdk:"description"`
	Disabled            types.Bool           `tfsdk:"disabled"`
	DisableNativeModule types.Bool           `tfsdk:"disable_native_module"`
	Environment         types.String         `tfsdk:"environment"`
	EventFormat         types.String         `tfsdk:"event_format"`
	ID                  types.String         `tfsdk:"id"`
	Interval            types.Number         `tfsdk:"interval"`
	LogNames            []types.String       `tfsdk:"log_names"`
	MaxEventBytes       types.Number         `tfsdk:"max_event_bytes"`
	Metadata            []Input51Metadata    `tfsdk:"metadata"`
	Pipeline            types.String         `tfsdk:"pipeline"`
	Pq                  *Input51Pq           `tfsdk:"pq"`
	PqEnabled           types.Bool           `tfsdk:"pq_enabled"`
	ReadMode            types.String         `tfsdk:"read_mode"`
	SendToRoutes        types.Bool           `tfsdk:"send_to_routes"`
	Status              *Input51Status       `tfsdk:"status"`
	Streamtags          []types.String       `tfsdk:"streamtags"`
	Type                types.String         `tfsdk:"type"`
}
