// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type InputDatagenSamples struct {
	EventsPerSec types.Float64 `tfsdk:"events_per_sec"`
	Sample       types.String  `tfsdk:"sample"`
}
