// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Input54Status struct {
	Health    types.String    `tfsdk:"health"`
	Metrics   *Input54Metrics `tfsdk:"metrics"`
	Timestamp types.Number    `tfsdk:"timestamp"`
}
