// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Input47Status struct {
	Health    types.String `tfsdk:"health"`
	Metrics   *Metrics     `tfsdk:"metrics"`
	Timestamp types.Number `tfsdk:"timestamp"`
}
