// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type Metrics struct {
	Buffered types.Number `tfsdk:"buffered"`
	Dropped  types.Number `tfsdk:"dropped"`
	Received types.Number `tfsdk:"received"`
}
