// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package globals

type Globals struct {
	OrganizationID *string `pathParam:"style=simple,explode=false,name=organizationId"`
	WorkspaceID    *string `pathParam:"style=simple,explode=false,name=workspaceId"`
	WorkerGroupID  *string `pathParam:"style=simple,explode=false,name=workerGroupId"`
}

func (o *Globals) GetOrganizationID() *string {
	if o == nil {
		return nil
	}
	return o.OrganizationID
}

func (o *Globals) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *Globals) GetWorkerGroupID() *string {
	if o == nil {
		return nil
	}
	return o.WorkerGroupID
}
